### ISSUE TITLE
Some weapons don't have ammunition when given by the case

### ISSUE THREAD

**Issue by tobi-nb** [menof36go/ttt2-t-suitcase#1]
Hey,

it seems as if some weapons, i.e. the standard RPG from HL2 don't have ammunition when they are given by the case. No error occurs in the log when this happens. The RPG is the only weapon I encountered this bug, yet.

**Comment by mexikoedi** [comment]
I couldn't reproduce this issue. I tested it with the RPG from "PolyShark" and I got 3 ammo. Maybe your RPG version is not TTT compatible? You need to reload the RPG but this is because of the RPG addon. If you find another item where you think it might be broken (or with no ammo) because of the suitcase please open a new issue.
